service: serverless-bolt-js
frameworkVersion: "4"
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs18.x
  deploymentMethod: direct
functions:
  slack:
    handler: dist/app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
useDotenv: true
custom:
  dotenv:
    exclude:
      - GITHUB_TOKEN
